version: 2
updates:
- package-ecosystem: gomod
  directory: "/"
  schedule:
    interval: weekly
    time: "04:00"
  open-pull-requests-limit: 10

- package-ecosystem: github-actions
  directory: '/'
  schedule:
    interval: daily
  target-branch: main

- package-ecosystem: docker
  directory: '/'
  schedule:
    interval: weekly
  target-branch: main

- package-ecosystem: docker
  directory: '.devcontainers/'
  schedule:
    interval: weekly
  target-branch: main
