name: Linting with golangci-lint
on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths-ignore:
      - "**.md"
      - "*.yml"
      - "Makefile"
      - "docs/*.md"
      - ".gitignore"
      - "LICENSE"
      - ".github/*.yml"
      - ".github/ISSUE_TEMPLATE/*.md"
      - ".github/*.md"
      - ".github/workflows/main.yml"
      - ".github/workflows/release.yml"
  pull_request:
    paths-ignore:
      - "**.md"
      - "*.yml"
      - "Makefile"
      - "docs/*.md"
      - ".gitignore"
      - "LICENSE"
      - ".github/*.yml"
      - ".github/ISSUE_TEMPLATE/*.md"
      - ".github/*.md"
      - ".github/workflows/main.yml"
      - ".github/workflows/release.yml"
jobs:
  golangci:
    name: Linter
    runs-on: ubuntu-latest
    permissions:
        contents: read
        pull-requests: read
    steps:
      - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c
      - uses: actions/setup-go@fac708d6674e30b6ba41289acaab6d4b75aa0753
        with:
          go-version: 1.20.X
      - uses: golangci/golangci-lint-action@08e2f20817b15149a52b5b3ebe7de50aff2ba8c5
        with:
          version: latest
