name: Linting with golangci-lint
on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths-ignore:
      - "**.md"
      - "*.yml"
      - "Makefile"
      - "docs/*.md"
      - ".gitignore"
      - "LICENSE"
      - ".github/*.yml"
      - ".github/ISSUE_TEMPLATE/*.md"
      - ".github/*.md"
      - ".github/workflows/main.yml"
      - ".github/workflows/release.yml"
  pull_request:
    paths-ignore:
      - "**.md"
      - "*.yml"
      - "Makefile"
      - "docs/*.md"
      - ".gitignore"
      - "LICENSE"
      - ".github/*.yml"
      - ".github/ISSUE_TEMPLATE/*.md"
      - ".github/*.md"
      - ".github/workflows/main.yml"
      - ".github/workflows/release.yml"
jobs:
  golangci:
    name: Linter
    runs-on: ubuntu-latest
    permissions:
        contents: read
        pull-requests: read
    steps:
      - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c
      - uses: actions/setup-go@93397bea11091df50f3d7e59dc26a7711a8bcfbe
        with:
          go-version: 1.20.X
      - uses: golangci/golangci-lint-action@3a919529898de77ec3da873e3063ca4b10e7f5cc
        with:
          version: latest
