name: "PR label assigner"

on:
  workflow_dispatch:
  pull_request:
    branches:
    - master
    - main
  pull_request_target:
    branches:
    - main
    - master

jobs:
  triage:
    permissions:
      checks: write
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@ac9175f8a1f3625fd0d4fb234536d26811351594
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          sync-labels: true