name: "PR label assigner"

on:
  workflow_dispatch:
  pull_request:
    branches:
    - master
    - main
  pull_request_target:
    branches:
    - main
    - master

jobs:
  triage:
    permissions:
      checks: write
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@9fcb2c2f5584144ca754f8bfe8c6f81e77753375
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          sync-labels: true