name: Golang testing
on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths-ignore:
      - "**.md"
      - "*.yml"
      - "Makefile"
      - "docs/*.md"
      - ".gitignore"
      - "LICENSE"
      - ".github/*.yml"
      - ".github/ISSUE_TEMPLATE/*.md"
      - ".github/*.md"
      - ".github/workflows/release.yml"
  pull_request:
    paths-ignore:
      - "**.md"
      - "*.yml"
      - "Makefile"
      - "docs/*.md"
      - ".gitignore"
      - "LICENSE"
      - ".github/*.yml"
      - ".github/ISSUE_TEMPLATE/*.md"
      - ".github/*.md"
      - ".github/workflows/release.yml"
jobs:
  testing:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    strategy:
      matrix:
        go: [1.17.x, 1.18.x, 1.19.X, 1.20.x]
    name: Go ${{ matrix.go }} check
    steps:
      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac
      - uses: actions/setup-go@93397bea11091df50f3d7e59dc26a7711a8bcfbe
        with:
          go-version: ${{ matrix.go }}
      - run: go test -v -failfast ./...
